### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by jasonfarrell** [jasonfarrell/my-repo#1]
- [ ] Google Analytics Pageview tracking
- [ ] Google Analytics events
- [ ] Metadata updating on state change
- [ ] Twitter Share
- [ ] Facebook Share
- [ ] 301 Redirects
- [ ] QA - IE 10+
- [ ] QA - iOS
- [ ] QA - Android
- [ ] QA - Landscape mobile
- [ ] QA - Safari
- [ ] QA - Firefox
- [ ] QA - Chrome
- [ ] QA - Slower connections
- [ ] Clarify with client launch plan (launch middle of the week if possible)
- [ ] Light ADA pass
- [ ] Favicon
- [ ] Correct legal links
- [ ] Performance check (reduce image sizes)
- [ ] Backup old site if needed
- [ ] Handle 404 errors (prerender-status-code tag)
- [ ] Test form functionality
- [ ] Form validation
- [ ] Newsletter
- [ ] If necessary, update endpoints to point at production
- [ ] Fix console errors
- [ ] Ensure social links are pointing to the right place
- [ ] Gain access to client’s server
- [ ] www issues
- [ ] https issues
- [ ] Ensure that host performance settings can handle site
- [ ] Google webmaster indexing
- [ ] Google webmaster sitemap
- [ ] Make sure fonts are purchased and fonts are pointing at correct domain (if applicable)
- [ ] https://web.dev/measure
